### ISSUE TITLE
Create documentation skeleton

### ISSUE THREAD

**Issue by vincentauger** [dfo-osdt/osp-docs#2]
# Draft Outline of Open Science Portal User Guide

1. **Introduction**
   - Welcome: A brief welcoming message introducing the user to the guide.
   - Purpose: Explain the purpose and importance of the user guide.
   - Audience: Describe the target audience for the guide (e.g., researchers, division managers, etc.).

2. **Getting Started**
   - System Requirements: Outline the browser prerequisites for using the application.
   - Login/Registration: Explain how to create an account or log in to the application.

3. **User Interface Overview**
   - Dashboard: Describe the main dashboard and its components.
   - Navigation: Explain how to navigate through the application.
   - Menus and Icons: Describe the purpose of menus and icons used in the interface.
   - Settings: Provide information on user settings and preferences.

4. **Using the Application**
   - Core Features: Detail the primary functions and features of the application.
   - Step-by-Step Tutorials: Offer tutorials or walkthroughs for common tasks or workflows (divided by type of user: author, manager, comms...)
   - Data Input: Explain how to input and manage data within the application.
   - Search Functionality: Describe how to search for specific information.

5. **Customization and Security (User Profile)**
   - User Preferences: Explain how users can customize their experience.
   - Security: Password resets, login history.
   - Updating and maintaining information in their profile
   
6. **Advanced Features**
   - Integration: If your application integrates with other tools or services, provide instructions for integration.
     1. ORCID integration: Provide guidance on linking/creating an ORCID.
     2. GoC Science Profiles sync: This feature.
   - [Lower priority] API Documentation: If applicable, include documentation for developers on how to use your API.

7. **Troubleshooting**
   - Common Issues: List and describe common problems users may encounter.
   - Error Messages: Explain error messages and how to resolve associated issues.
   - FAQs: Include frequently asked questions and their answers.

8. **Support and Contact**
   - Contact Information: Provide contact details for customer support or help resources.
   - Feedback: Encourage users to provide feedback on the guide or the application itself.

9. **Updates and Version History**
   - Release Notes: Keep a record of updates, new features, and bug fixes.
   - Version History: List previous versions of the application and their changes.

10. **Appendices**
    - Glossary: Include a glossary of terms used in the application.
    - References: Provide links to additional resources or related documentation (publication policy, guide, acts and legislations...).
    - Index: Create an index for quick reference.

11. **Legal and Compliance**
    - Terms of Service: Link to your application's terms of service or user agreement.
    - Privacy Policy: Link to your application's privacy policy.

12. **Acknowledgments**
    - Thank users for choosing your application and acknowledge contributors if applicable.

**Comment by MathewEm** [comment]
Skeleton created but needs basic population
