### ISSUE TITLE
Double Check Strip Formatting in Rich Text boxes (Section 4)

### ISSUE THREAD

**Issue by vincentauger** [dfo-osdt/osp-docs#9]
"If you choose to copy-paste your summary, please remember that the text-box will strip all text formatting." Just noticed this, text box should retain the majority of the supported text formatting - is everything stripped now?

**Comment by MathewEm** [comment]
Bolding, italics, and indents are preserved when copy-pasting from a word document. I will update the docs to remove this stripping warning.
